name: Deploy Node Application

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> .env

       - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        working-directory: ./backend  # Specify the path to the backend folder
        run: docker build -t pr1y4nk4/farmtodo0r-backend .  # Use the correct Docker image name
      
      - name: Publish image to Docker Hub
        run: docker push pr1y4nk4/farmtodo0r-backend:latest

  deploy:
    needs: build
    runs-on: node
    steps:
      - name: Pull image from Docker Hub
        run: docker pull pr1y4nk4/farmtodo0r-backend:latest  # Correct Docker image name

      - name: Delete old container
        run: docker rm -f nodejs-app-container || true

      - name: Run Docker container
        run: docker run -d -p 5000:5000 --name nodejs-app-container -e MONGODB_URL='${{ secrets.MONGODB_URL }}' pr1y4nk4/farmtodo0r-backend