name: Deploy Node Application

on: 
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
      working-directory: ./frontend  # Specify the path to the backend folder
        run: docker build -t pr1y4nk4/frontend . 
      - name: Publish Image to docker hub
        run: docker push pr1y4nk4/frontend:latest 
 
  deploy:
    needs: build
    runs-on: ip-172-31-39-54
    steps:
      - name: Pull image from docker hub
        run: docker pull pr1y4nk4/frontend:latest 
      - name: Delete old container
        run: docker rm -f reactjs-app-container
      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name reactjs-app-container pr1y4nk4/frontend